# -*- coding: utf-8 -*-
"""syn_flood_simulation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SvGJUDBobIk1o95_8IjWxBZhlJaPjEXF
"""

import numpy as np
import matplotlib.pyplot as plt

# TCP SYN Flood Simulation

# Timeline
T = 120                      # total simulation time (seconds)
dt = 1                       # time step
time = np.arange(0, T + dt, dt)

# Server settings
backlog_capacity = 100       # maximum half-open connections the server can hold
normal_timeout = 20          # seconds before half-open states expire (no mitigation)
mitigated_timeout = 6        # reduced timeout with mitigation
legit_users_per_sec = 8      # legitimate connection attempts per second

# Attack profile
attack_start = 20
attack_end = 80
attack_syn_rate = 18         # simulated malicious SYN arrivals per second

# Mitigation profile
mitigation_enabled = True
mitigation_start = 80
syn_cookie_effect = 0.55     # fraction of malicious half-open load neutralised
filter_effect = 0.25         # fraction filtered before consuming backlog

# State arrays
half_open = np.zeros_like(time, dtype=float)
backlog_usage_pct = np.zeros_like(time, dtype=float)
legit_success_rate = np.zeros_like(time, dtype=float)
latency_ms = np.zeros_like(time, dtype=float)

# Queue to track half-open expiry
pending_half_open = []

for i, t in enumerate(time):
    # Expire old half-open entries
    pending_half_open = [expiry for expiry in pending_half_open if expiry > t]

    current_half_open = len(pending_half_open)

    # Determine timeout and mitigation
    if mitigation_enabled and t >= mitigation_start:
        timeout_value = mitigated_timeout
        effective_attack_rate = attack_syn_rate * (1 - syn_cookie_effect) * (1 - filter_effect)
    else:
        timeout_value = normal_timeout
        effective_attack_rate = attack_syn_rate

    # Add malicious half-open connections during attack window
    if attack_start <= t < attack_end:
        new_attack_syn = int(round(effective_attack_rate))
        available_slots = max(0, backlog_capacity - len(pending_half_open))
        accepted_attack_syn = min(new_attack_syn, available_slots)
        for _ in range(accepted_attack_syn):
            pending_half_open.append(t + timeout_value)

    current_half_open = len(pending_half_open)

    # Backlog usage
    usage = current_half_open / backlog_capacity
    backlog_usage_pct[i] = usage * 100
    half_open[i] = current_half_open

    # Legitimate success rate model
    # As backlog fills, fewer legitimate users complete connection
    remaining_capacity_ratio = max(0, 1 - usage)
    success = max(0.05, remaining_capacity_ratio)  # keep a small floor for visibility
    if mitigation_enabled and t >= mitigation_start:
        success = min(1.0, success + 0.35)  # mitigation improves completion chance

    legit_success_rate[i] = success * 100

    # Latency model
    # As backlog fills, handshake delays and retries increase
    latency = 40 + 4 * current_half_open
    if mitigation_enabled and t >= mitigation_start:
        latency *= 0.65
    latency_ms[i] = latency

# Plot 1: Half-open connections
plt.figure(figsize=(10, 5))
plt.plot(time, half_open, linewidth=2)
plt.axvline(attack_start, linestyle='--', label='Attack starts')
plt.axvline(mitigation_start, linestyle='--', label='Mitigation starts')
plt.title("Simulated Half-Open TCP Connections")
plt.xlabel("Time (s)")
plt.ylabel("Half-open connections")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.savefig("half_open_connections.png", dpi=300)
plt.show()

# Plot 2: Backlog usage
plt.figure(figsize=(10, 5))
plt.plot(time, backlog_usage_pct, linewidth=2)
plt.axvline(attack_start, linestyle='--', label='Attack starts')
plt.axvline(mitigation_start, linestyle='--', label='Mitigation starts')
plt.title("Simulated Server Backlog Usage")
plt.xlabel("Time (s)")
plt.ylabel("Backlog usage (%)")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.savefig("backlog_usage.png", dpi=300)
plt.show()

# Plot 3: Legitimate success rate
plt.figure(figsize=(10, 5))
plt.plot(time, legit_success_rate, linewidth=2)
plt.axvline(attack_start, linestyle='--', label='Attack starts')
plt.axvline(mitigation_start, linestyle='--', label='Mitigation starts')
plt.title("Legitimate Connection Success Rate")
plt.xlabel("Time (s)")
plt.ylabel("Success rate (%)")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.savefig("legitimate_success_rate.png", dpi=300)
plt.show()

# Plot 4: Latency
plt.figure(figsize=(10, 5))
plt.plot(time, latency_ms, linewidth=2)
plt.axvline(attack_start, linestyle='--', label='Attack starts')
plt.axvline(mitigation_start, linestyle='--', label='Mitigation starts')
plt.title("Estimated Connection Latency")
plt.xlabel("Time (s)")
plt.ylabel("Latency (ms)")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.savefig("latency_estimate.png", dpi=300)
plt.show()

print("Simulation completed.")
print("Generated figures:")
print("- half_open_connections.png")
print("- backlog_usage.png")
print("- legitimate_success_rate.png")
print("- latency_estimate.png")

!pwd
!ls
!whoami

for i, t in enumerate(time):
    if t in [0, 20, 40, 60, 80, 100, 120]:
        print(f"[t={t:3d}s] half_open={half_open[i]:.0f}, backlog={backlog_usage_pct[i]:.1f}%, success={legit_success_rate[i]:.1f}%, latency={latency_ms[i]:.1f}ms")